### ISSUE TITLE
无法运行， Android NDK: Aborting    .  Stop.

### ISSUE THREAD

**Issue by Knight-ZXW** [wnpllrzodiac/BiBo#1]
...\sdk\ndk-bundle\build\core\prebuilt-library.mk
   Execution failed for task :'app:ndkBuild'.
Error:Execution failed for task ':app:ndkBuild'.
> Process 'command 'D:\Android\sdk\ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2

我是AS 2.2.3 ，执行项目后报以上错误，

**Comment by wnpllrzodiac** [comment]
请在项目根目录 手动配置文件 local.properties

请先下载thirdparty库，解压至指定目录 BiBo/app/src/main/jni
├─jni
│  ├─facedetect
│  │  ├─com.jiuyan.infashion
│  │  ├─com.smile.gifmaker
│  │  └─faceunity
│  ├─fdk-aac
│  │  ├─include
│  │  │  └─fdk-aac
│  │  └─lib
│  ├─ffmpeg
│  │  ├─include
│  │  │  ├─libavcodec
│  │  │  ├─libavformat
│  │  │  ├─libavutil
│  │  │  └─libswresample
│  │  └─lib
│  ├─libyuv
│  │  ├─include
│  │  │  └─libyuv
│  │  └─lib
│  ├─rtmpdump
│  │  ├─include
│  │  │  ├─librtmp
│  │  │  └─openssl
│  │  └─lib
│  └─x264
│      ├─include
│      └─lib

在项目根目录下执行 gradle assembleRelease 即可编译jni 和java工程

windows下示例
```
ndk.dir=D\:\\software\\Android\\android-ndk-r13
sdk.dir=C\:\\Users\\Lenovo\\AppData\\Local\\Android\\sdk
```
linux下示例
```
sdk.dir=/usr/local/android-sdk-linux
ndk.dir=/usr/local/android-ndk-r13
```

**Comment by wnpllrzodiac** [comment]
thirdpary lib path updated:
http://oeuwkyzut.bkt.clouddn.com/bibo_thirdparty_lib_v4.7z

**Comment by wnpllrzodiac** [comment]
Nice!

**Comment by Knight-ZXW** [comment]
您好，如果方便的话，我还想问一个问题，这个项目代码量很多，
我之前没做过视频方面的开发，现在我的项目有个 需求是 做 本地的短视频录制 需要加滤镜 和 背景音 以及混音的功能，不需要rmtp推流 。我想把这个项目的功能精简成我的需求，但是我对jni 目录下的那些.h .c 。比如 andqueue.c andstack 什么的 这些零散的文件，我无法区分是不是我的功能锁需要的，
